// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwsdF5z6qCuSRUfNjiCH9V4gnSydVK4ks',
    appId: '1:571599438765:web:5c1adabce3ed0212f55724',
    messagingSenderId: '571599438765',
    projectId: 'cs-1635-example',
    authDomain: 'cs-1635-example.firebaseapp.com',
    storageBucket: 'cs-1635-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANV9thb7G0kclslE-pGMkPR7IEf_sgoPo',
    appId: '1:571599438765:android:199fd96685940ca9f55724',
    messagingSenderId: '571599438765',
    projectId: 'cs-1635-example',
    storageBucket: 'cs-1635-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgNG8RpNfwx-ABrZVnzF7Pz8MTO8pLiEc',
    appId: '1:571599438765:ios:4d881abc6051229cf55724',
    messagingSenderId: '571599438765',
    projectId: 'cs-1635-example',
    storageBucket: 'cs-1635-example.appspot.com',
    iosClientId: '571599438765-37r1uks1d1msp2rprjqbe4lqutgj4jpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgNG8RpNfwx-ABrZVnzF7Pz8MTO8pLiEc',
    appId: '1:571599438765:ios:4d881abc6051229cf55724',
    messagingSenderId: '571599438765',
    projectId: 'cs-1635-example',
    storageBucket: 'cs-1635-example.appspot.com',
    iosClientId: '571599438765-37r1uks1d1msp2rprjqbe4lqutgj4jpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );
}
